package com.will.entities.enums;

public enum CategoriaDosGastos {
	
	PAGAMENTO_PRESTADOR_DE_SERVICO,
	MANUTENCAO_EQUIPAMENTO,
	MANUTENCAO_CARRO,
	ABASTECIMENTO_EQUIPAMENTO,
	ABASTECIMENTO_CARRO,
	COMPRA_DE_EQUIPAMENTO,
	COMPRA_DE_PRODUTO,
	COMPRA_AUTOMOVEL,
	ADIANTAMENTO_PRESTADOR_DE_SERVICO,
	RETIRADA;
	
}
